# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(to='api.Company'),
        ),
    ]
