# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='catalogs',
        ),
    ]
