# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_catalogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='api.Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.Company'),
        ),
    ]
