# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180920_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='catalog',
            field=models.ManyToManyField(to='api.Catalog'),
        ),
    ]
