# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180920_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='company_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
