# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180920_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
