# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='catalog_id',
            field=models.ManyToManyField(to='api.Catalog'),
        ),
    ]
