# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_company_catalog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='catalog_id',
            new_name='catalogs',
        ),
    ]
